name: npm-release
on:
  release:
    types:
      - published

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: yarn test --ci --coverage --maxWorkers=2

  publish-npm:
    needs: test
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish-github:
  #   needs: test
  #   name: Publish to GitHub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - name: Configure Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12'
  #         registry-url: 'https://npm.pkg.github.com'
  #     - name: Install dependencies
  #       uses: bahmutov/npm-install@v1
  #     - name: Publish
  #       run: yarn publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
